# -*- coding: utf-8 -*-
"""SPR_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdVuAddYc3KpfACgo0Q0ms4zMUjdSgwS

**Generating Dataset Based on Kaggle Data**
"""

import pandas as pd
import numpy as np
import random

# Reproducibility
np.random.seed(42)
random.seed(42)

# Sample names
first_names = [
    "John","Sarah","Alex","Michael","Emma","Olivia","Daniel","Sophia",
    "James","Isabella","Liam","Ava","Noah","Mia","Ethan","Charlotte",
    "Lucas","Amelia","Benjamin","Harper","Elijah","Evelyn","Henry",
    "Abigail","Alexander","Emily","Matthew","Ella","David","Scarlett"
]

genders = ["Male", "Female"]
parent_support = ["Low", "Medium", "High"]

data = []

for i in range(1, 1001):

    name = random.choice(first_names)
    gender = random.choice(genders)

    attendance = np.random.randint(60, 101)        # 60-100%
    study_hours = np.random.randint(5, 36)         # 5-35 hrs/week
    previous_grade = np.random.randint(50, 96)     # 50-95
    extracurricular = np.random.randint(0, 4)      # 0-3
    parental = random.choice(parent_support)

    # Bonuses
    parental_bonus = {
        "Low": 0,
        "Medium": 2,
        "High": 5
    }[parental]

    extra_bonus = extracurricular * 1.5

    # Final Grade Formula
    final_grade = (
        0.35 * previous_grade +
        0.30 * attendance +
        0.25 * study_hours +
        parental_bonus +
        extra_bonus +
        np.random.normal(0, 3)
    )

    final_grade = round(max(40, min(100, final_grade)))

    data.append([
        i,
        name,
        gender,
        attendance,
        study_hours,
        previous_grade,
        extracurricular,
        parental,
        final_grade
    ])

# Create DataFrame
df = pd.DataFrame(data, columns=[
    "StudentID",
    "Name",
    "Gender",
    "AttendanceRate",
    "StudyHoursPerWeek",
    "PreviousGrade",
    "ExtracurricularActivities",
    "ParentalSupport",
    "FinalGrade"
])

# Save CSV
df.to_csv("student_performance_1000.csv", index=False)

print(df.head())
print("\nDataset Shape:", df.shape)

"""**Installing Required Libraries**"""

pip install pandas numpy scikit-learn matplotlib seaborn

"""**Loading Dataset**"""

import pandas as pd

df = pd.read_csv("student_performance_1000.csv")

print(df.head())
print(df.info())

"""**Converting Features**"""

from sklearn.preprocessing import LabelEncoder

le_gender = LabelEncoder()
le_parent = LabelEncoder()

df["Gender"] = le_gender.fit_transform(df["Gender"])
df["ParentalSupport"] = le_parent.fit_transform(df["ParentalSupport"])

"""**Selecting Features**"""

X = df[
    [
        "Gender",
        "AttendanceRate",
        "StudyHoursPerWeek",
        "PreviousGrade",
        "ExtracurricularActivities",
        "ParentalSupport"
    ]
]

y = df["FinalGrade"]

"""**Split Dataset**"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""**Train Random Forest**"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""**Evaluate Model**"""

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
from sklearn.ensemble import RandomForestRegressor

# Initialize and train a RandomForestRegressor model
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred) ** 0.5
r2 = r2_score(y_test, y_pred)

print("MAE:", round(mae,2))
print("RMSE:", round(rmse,2))
print("R² Score:", round(r2,2))

"""**Feature Importance**"""

import matplotlib.pyplot as plt

importance = model.feature_importances_

features = X.columns

plt.figure(figsize=(8,5))
plt.barh(features, importance)
plt.title("Feature Importance")
plt.xlabel("Importance")
plt.tight_layout()
plt.show()

"""**Save Model**"""

import pickle

with open("student_model.pkl", "wb") as f:
    pickle.dump(model, f)

print("Model Saved!")

"""**Test Prediction**"""

sample = [[
    1,      # Gender
    90,     # Attendance
    20,     # Study Hours
    85,     # Previous Grade
    2,      # Extracurricular
    2       # High Parental Support
]]

prediction = model.predict(sample)

print("Predicted Final Grade:", round(prediction[0],2))